<p><a href="<?php echo $this->url(
        array(
            'controller' => 'guestbook',
            'action'     => 'sign'
        ),
        'default',
        true) ?>">Sign Our Guestbook</a></p>

<style type="text/css">
    TABLE {
        width: 500px; /* Ширина таблицы */
        border-collapse: collapse; /* Убираем двойные линии между ячейками */
    }
    TD, TH {
        padding: 3px; /* Поля вокруг содержимого таблицы */
        border: 1px solid black; /* Параметры рамки */
    }
    TH {
        background: #b0e0e6; /* Цвет фона */
    }
</style>
<table>
    <tr>
        <th>Имя пользователя</th><th>E-mail</th><th>Комментарий</th><th>Дата создания</th>
    </tr>
    <tr>
    <?php foreach ($this->entries as $entry): ?>
        <td><?php echo $this->escape($entry->username) ?></td>
        <td><?php echo $this->escape($entry->email) ?></td>
        <td><?php echo $this->escape($entry->comment) ?></td>
        <td><?php echo $this->escape($entry->created) ?></td>
    </tr>
    <?php endforeach ?>

</table>
